// <auto-generated />
namespace ColorOasisSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class QuotationModified3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuotationModified3));
        
        string IMigrationMetadata.Id
        {
            get { return "202406262104267_QuotationModified3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
