namespace ColorOasisSystem.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UserPermission : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.UserPermissions", "UserUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "UserUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "UserUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "UserUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "UserUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "UserUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientSecondUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientWorkUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "WelcomeUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ServiceUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "InspectionUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "QuotationUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "ClientTransUCPermission_Additional", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "CompanyTransUCPermission_Additional", c => c.Boolean(nullable: false));
            DropColumn("dbo.UserPermissions", "PermissionOfUser_Lock");
            DropColumn("dbo.UserPermissions", "PermissionOfUser_AddNew");
            DropColumn("dbo.UserPermissions", "PermissionOfUser_Edit");
            DropColumn("dbo.UserPermissions", "PermissionOfUser_Delete");
            DropColumn("dbo.UserPermissions", "PermissionOfUser_Retrive");
            DropColumn("dbo.UserPermissions", "PermissionOfPermission_Lock");
            DropColumn("dbo.UserPermissions", "PermissionOfPermission_AddNew");
            DropColumn("dbo.UserPermissions", "PermissionOfPermission_Edit");
            DropColumn("dbo.UserPermissions", "PermissionOfPermission_Delete");
            DropColumn("dbo.UserPermissions", "PermissionOfPermission_Retrive");
        }
        
        public override void Down()
        {
            AddColumn("dbo.UserPermissions", "PermissionOfPermission_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfPermission_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfPermission_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfPermission_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfPermission_Lock", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfUser_Retrive", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfUser_Delete", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfUser_Edit", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfUser_AddNew", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserPermissions", "PermissionOfUser_Lock", c => c.Boolean(nullable: false));
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "CompanyTransUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ClientTransUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "CompanyPaymentUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ClientPaymentUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "QuotationUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "InspectionUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "CompanyUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ClientUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ServiceUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ServiceCategoryUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ServiceTypeUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "WelcomeUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "SettingsSecondUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ServiceSecondUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ClientWorkUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "ClientSecondUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "CompanyInfoUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "SettingsUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "PermissionUCPermission_Lock");
            DropColumn("dbo.UserPermissions", "UserUCPermission_Additional");
            DropColumn("dbo.UserPermissions", "UserUCPermission_Retrive");
            DropColumn("dbo.UserPermissions", "UserUCPermission_Delete");
            DropColumn("dbo.UserPermissions", "UserUCPermission_Edit");
            DropColumn("dbo.UserPermissions", "UserUCPermission_AddNew");
            DropColumn("dbo.UserPermissions", "UserUCPermission_Lock");
        }
    }
}
